version: "3"
 
services:
  job-portal:
    container_name: job-portal
    image: job-portal-api:latest
    ports:
      - "8081:8081"
    build: .
    env_file:
      - .app.env
      - .db.env
      - .postgres.env
      - .redis.env
      - .keys.env
    depends_on:
      - postgres
      - redis
    restart: always
  redis:
    container_name: my-redis-container
    image: redis
    ports:
      - "6379:6379"  
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .postgres.env
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=admin
    #   - POSTGRES_DB=job-portal-app